const defaultOverview =
  "This course is specially designed for students who want to build professional skills and start their career in the creative industry. Students will work on live projects, portfolio development, software training, and industry workflows."

const defaultLearn = [
  "Fundamentals",
  "Industry Workflow",
  "Portfolio Development",
  "Live Projects",
  "Creative Thinking",
  "Professional Editing",
  "Color Theory",
  "Advanced Techniques",
]

const defaultSoftware = [
  "Photoshop",
  "Illustrator",
  "Lightroom",
  "Premiere Pro",
  "After Effects",
  "Blender",
  "Maya",
  "Canva",
]

const defaultCareers = [
  "Graphic Designer",
  "Digital Artist",
  "Photo Editor",
  "Content Creator",
  "Freelancer",
  "Creative Director",
]

export const courseData = [
  {
    id: 1,
    title: "Digital Photography",
    image: "/modern-animation-studio-with-students-working-on-c.jpg",
    duration: "6 Months",
    fees: "₹35,000",
    description: "Professional Photography Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
    images: [
      "/digitalpgotography1.jpg",
      "/digitalpgotography2.jpg",
      "/digitalpgotography3.jpg",
    ],
  },
  {
    id: 2,
    title: "Digital Marketing",
    image: "/digital-marketing-analytics-dashboard.jpg",
    duration: "6 Months",
    fees: "₹30,000",
    description: "Digital Marketing Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
    images: [
      "/dgmarketing3.jpg",
      "/dgmarketing2.jpg",
      "/dgmarketing1.jpg",
    ],
  },
  {
    id: 3,
    title: "Web Designing",
    image: "/web-development-and-responsive-design.jpg",
    duration: "6 Months",
    fees: "₹32,000",
    description: "Web Designing Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
  },
  {
    id: 4,
    title: "Fashion Design",
    image: "/cartoon-character-design-sheet.jpg",
    duration: "6 Months",
    fees: "₹34,000",
    description: "Fashion Design Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
  },
  {
    id: 5,
    title: "Interior Design",
    image: "/fantasy-game-environment-with-castle.jpg",
    duration: "6 Months",
    fees: "₹33,000",
    description: "Interior Design Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
    images: [
      "/interior1.jpg",
      "/interior2.jpg",
      "/interior3.jpg",
    ],
  },
  {
    id: 6,
    title: "Animation",
    image: "/3d-character-animation-scene.jpg",
    duration: "6 Months",
    fees: "₹36,000",
    description: "Animation Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
  },
  {
    id: 7,
    title: "Visual Effects",
    image: "/vfx-compositing-and-special-effects.jpg",
    duration: "6 Months",
    fees: "₹37,000",
    description: "Visual Effects Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
  },
  {
    id: 8,
    title: "Game Arts And Design",
    image: "/game-character-design-and-3d-modeling.jpg",
    duration: "6 Months",
    fees: "₹36,000",
    description: "Game Arts And Design Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
  },
  {
    id: 9,
    title: "Graphic Design",
    image: "/graphic-design-portfolio-and-branding.jpg",
    duration: "6 Months",
    fees: "₹31,000",
    description: "Graphic Design Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
  },
  {
    id: 10,
    title: "UI/UX Design",
    image: "/modern-website-design-mockup.jpg",
    duration: "6 Months",
    fees: "₹32,000",
    description: "UI/UX Design Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
  },
];