const defaultOverview =
  "This course is specially designed for students who want to build professional skills and start their career in the creative industry. Students will work on live projects, portfolio development, software training, and industry workflows."

const defaultLearn = [
  "Fundamentals",
  "Industry Workflow",
  "Portfolio Development",
  "Live Projects",
  "Creative Thinking",
  "Professional Editing",
  "Color Theory",
  "Advanced Techniques",
]

const defaultSoftware = [
  "Photoshop",
  "Illustrator",
  "Lightroom",
  "Premiere Pro",
  "After Effects",
  "Blender",
  "Maya",
  "Canva",
]

const defaultCareers = [
  "Graphic Designer",
  "Digital Artist",
  "Photo Editor",
  "Content Creator",
  "Freelancer",
  "Creative Director",
]

export const courseData = [
  {
    id: 1,
    title: "Digital Photography",
    image: "/modern-animation-studio-with-students-working-on-c.jpeg",
    duration: "6 Months",
    fees: "₹xxxx",
    description: "Professional Photography Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
    images: [
      "/digitalpgotography1.jpg",
      "/digitalpgotography2.jpg",
      "/digitalpgotography3.jpg",
    ],
  },
  {
    id: 2,
    title: "Digital Marketing",
    image: "/digital-marketing-analytics-dashboard.jpg",
    duration: "6 Months",
    fees: "₹xxxx",
    description: "Digital Marketing Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
    images: [
      "/dgmarketing3.jpg",
      "/dgmarketing2.jpg",
      "/dgmarketing1.jpg",
    ],
  },
  {
    id: 3,
    title: "Web Designing",
    image: "/web-development-and-responsive-design.jpg",
    duration: "6 Months",
    fees: "₹xxxx",
    description: "Web Designing Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
  },
  {
    id: 4,
    title: "Fashion Design",
    image: "/cartoon-character-design-sheet.jpg",
    duration: "6 Months",
    fees: "₹xxxx",
    description: "Fashion Design Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
  },
  {
    id: 5,
    title: "Interior Design",
    image: "/fantasy-game-environment-with-castle.jpg",
    duration: "6 Months",
    fees: "₹xxxx",
    description: "Interior Design Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
    images: [
      "/interior1.jpg",
      "/interior2.jpg",
      "/interior3.jpg",
    ],
  },
  {
    id: 6,
    title: "Animation",
    image: "/3d-character-animation-scene.jpg",
    duration: "6 Months",
    fees: "₹xxxx",
    description: "Animation Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
  },
  {
    id: 7,
    title: "Visual Effects",
    image: "/vfx-compositing-and-special-effects.jpg",
    duration: "6 Months",
    fees: "₹xxxx",
    description: "Visual Effects Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
  },
  {
    id: 8,
    title: "Game Arts And Design",
    image: "/game-character-design-and-3d-modeling.jpg",
    duration: "6 Months",
    fees: "₹xxxx",
    description: "Game Arts And Design Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
  },
  {
    id: 9,
    title: "Graphic Design",
    image: "/graphic-design-portfolio-and-branding.jpg",
    duration: "6 Months",
    fees: "₹xxxx",
    description: "Graphic Design Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
  },
  {
    id: 10,
    title: "UI/UX Design",
    image: "/modern-website-design-mockup.jpg",
    duration: "6 Months",
    fees: "₹xxxx",
    description: "UI/UX Design Course",
    overview: defaultOverview,
    eligibility: "10th / 12th",
    learn: defaultLearn,
    software: defaultSoftware,
    careers: defaultCareers,
  },
  {
    id: 11,
    title: "CAD Architectural Model",
    image: "/cad_img2.png",
    duration: "6 Months",
    fees: "₹xxxx",
    description: "CAD Architectural Model Course",
    overview:
      "This course equips students with the practical skills required to create detailed architectural drawings, layouts, and presentations using industry-standard CAD tools. Students gain hands-on experience in drafting, measurement, planning, and visual communication for real-world projects.",
    eligibility: "10th / 12th / Diploma",
    learn: [
      "2D Drafting",
      "Architectural Planning",
      "Section & Elevation",
      "Interior Layouts",
      "Material Detailing",
      "Presentation Skills",
      "Site Planning",
      "3D Visualization",
    ],
    software: ["AutoCAD", "SketchUp", "Revit", "Photoshop", "Illustrator", "Lumion"],
    careers: [
      "CAD Draftsman",
      "Architectural Visualizer",
      "Interior Designer",
      "Site Planner",
      "Freelance Designer",
      "Construction Consultant",
    ],
    images: ["/cad_img1.jpg", "/cad_img2.png"],
  },
  {
    id: 12,
    title: "Coding",
    image: "/coding_img1.jpg",
    duration: "6 Months",
    fees: "₹xxxx",
    description: "Coding Course",
    overview:
      "This coding program focuses on practical web development, problem-solving, and project execution. Students learn building blocks of programming and modern interfaces while creating live projects that prepare them for real-world technical roles.",
    eligibility: "10th / 12th",
    learn: [
      "HTML & CSS",
      "JavaScript Fundamentals",
      "Responsive Design",
      "Logic Building",
      "Problem Solving",
      "React Basics",
      "Git & GitHub",
      "Project Development",
    ],
    software: ["VS Code", "GitHub", "HTML5", "CSS3", "JavaScript", "React"],
    careers: [
      "Frontend Developer",
      "Web Developer",
      "Junior Programmer",
      "UI Engineer",
      "Software Trainee",
      "Freelance Developer",
    ],
    images: ["/coding_img1.jpg"],
  },
];